
server:
  port: 8080
#  port: 8803
mybatis-plus:
  #实体类别名简称
  type-aliases-package: com.hang.tudou.tudouorder.entity
spring:
  #数据库
  datasource:
    url: jdbc:mysql://192.168.101.105:3306/tudou-oms


